name = "RamseySpectroscopyCore"
uuid = "c2a93995-efaf-4fb2-b3df-3b08479f64e0"
authors = ["Maksim Radchenko"]
version = "1.0.1"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
